DROP TABLE IF EXISTS bridge;
DROP TABLE IF EXISTS day;
DROP TABLE IF EXISTS opening;

CREATE TABLE bridge (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    full_title TEXT NOT NULL
);

CREATE TABLE day (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts DATE NOT NULL DEFAULT CURRENT_DATE,
);

CREATE TABLE opening (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    started_at TIME NOT NULL,
    closed_at TIME NOT NULL,
    FOREIGN KEY (day_id) REFERENCES day (id),
    FOREIGN KEY (bridge_id) REFERENCES bridge (id)
);
