# environmental variables

DB_PATH = 'bridges_database.db'

BRIDGE_CREATE = """CREATE TABLE IF NOT EXISTS bridge (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
full_title TEXT NOT NULL)"""

DAY_CREATE = """CREATE TABLE IF NOT EXISTS day (
id INTEGER PRIMARY KEY AUTOINCREMENT,
ts DATE NOT NULL DEFAULT CURRENT_DATE)"""

OPENING_CREATE = """CREATE TABLE IF NOT EXISTS opening (
id INTEGER PRIMARY KEY AUTOINCREMENT,
started_at TIME NOT NULL,
closed_at TIME NOT NULL,
FOREIGN KEY (id) REFERENCES day (id),
FOREIGN KEY (id) REFERENCES bridge (id))"""

INSERT_BRIDGE = """INSERT INTO bridge (title, full_title) VALUES (?, ?)"""
